<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.BatchGetRowRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * -*- magic methods -*-
 *
 * @method array getTables()
 * @method void appendTables(\ots\protocolbuffer\TableInBatchGetRowRequest $value)
 */
class BatchGetRowRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.BatchGetRowRequest)
  
  /**
   * @var array $tables
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \ots\protocolbuffer\TableInBatchGetRowRequest
   **/
  protected $tables;
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.BatchGetRowRequest)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.BatchGetRowRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "tables",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\TableInBatchGetRowRequest',
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.BatchGetRowRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
