<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.Condition)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * -*- magic methods -*-
 *
 * @method \ots\protocolbuffer\RowExistenceExpectation getRowExistence()
 * @method void setRowExistence(\ots\protocolbuffer\RowExistenceExpectation $value)
 */
class Condition extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.Condition)
  
  /**
   * @var \ots\protocolbuffer\RowExistenceExpectation $row_existence
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_ENUM
   * @see \ots\protocolbuffer\RowExistenceExpectation
   **/
  protected $row_existence;
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.Condition)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.Condition)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "row_existence",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.Condition)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
