<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.DeleteTableResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * -*- magic methods -*-
 *
 */
class DeleteTableResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.DeleteTableResponse)
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.DeleteTableResponse)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.DeleteTableResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.DeleteTableResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
