<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.GetRangeRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * -*- magic methods -*-
 *
 * @method string getTableName()
 * @method void setTableName(\string $value)
 * @method \ots\protocolbuffer\Direction getDirection()
 * @method void setDirection(\ots\protocolbuffer\Direction $value)
 * @method array getColumnsToGet()
 * @method void appendColumnsToGet(\string $value)
 * @method string getLimit()
 * @method void setLimit(\string $value)
 * @method array getInclusiveStartPrimaryKey()
 * @method void appendInclusiveStartPrimaryKey(\ots\protocolbuffer\Column $value)
 * @method array getExclusiveEndPrimaryKey()
 * @method void appendExclusiveEndPrimaryKey(\ots\protocolbuffer\Column $value)
 */
class GetRangeRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.GetRangeRequest)
  
  /**
   * @var string $table_name
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $table_name;
  
  /**
   * @var \ots\protocolbuffer\Direction $direction
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_ENUM
   * @see \ots\protocolbuffer\Direction
   **/
  protected $direction;
  
  /**
   * @var array $columns_to_get
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_STRING
   **/
  protected $columns_to_get;
  
  /**
   * @var string $limit
   * @tag 4
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT32
   **/
  protected $limit;
  
  /**
   * @var array $inclusive_start_primary_key
   * @tag 5
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \ots\protocolbuffer\Column
   *
   * required all PKs, possibly filled with INF_MIN/INF_MAX
   *
   **/
  protected $inclusive_start_primary_key;
  
  /**
   * @var array $exclusive_end_primary_key
   * @tag 6
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \ots\protocolbuffer\Column
   *
   * required all PKs, possibly filled with INF_MIN/INF_MAX
   *
   **/
  protected $exclusive_end_primary_key;
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.GetRangeRequest)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.GetRangeRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "table_name",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_ENUM,
        "name"     => "direction",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_STRING,
        "name"     => "columns_to_get",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => "",
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "limit",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(5, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "inclusive_start_primary_key",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\Column',
      )));
      $desc->addField(6, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "exclusive_end_primary_key",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\Column',
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.GetRangeRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
