<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.GetRangeResponse)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * -*- magic methods -*-
 *
 * @method \ots\protocolbuffer\ConsumedCapacity getConsumed()
 * @method void setConsumed(\ots\protocolbuffer\ConsumedCapacity $value)
 * @method array getNextStartPrimaryKey()
 * @method void appendNextStartPrimaryKey(\ots\protocolbuffer\Column $value)
 * @method array getRows()
 * @method void appendRows(\ots\protocolbuffer\Row $value)
 */
class GetRangeResponse extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.GetRangeResponse)
  
  /**
   * @var \ots\protocolbuffer\ConsumedCapacity $consumed
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $consumed;
  
  /**
   * @var array $next_start_primary_key
   * @tag 2
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \ots\protocolbuffer\Column
   *
   * missing means hitting the end
   *
   **/
  protected $next_start_primary_key;
  
  /**
   * @var array $rows
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \ots\protocolbuffer\Row
   **/
  protected $rows;
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.GetRangeResponse)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.GetRangeResponse)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "consumed",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\ConsumedCapacity',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "next_start_primary_key",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\Column',
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "rows",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\Row',
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.GetRangeResponse)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
