<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.ReservedThroughputDetails)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * -*- magic methods -*-
 *
 * @method \ots\protocolbuffer\CapacityUnit getCapacityUnit()
 * @method void setCapacityUnit(\ots\protocolbuffer\CapacityUnit $value)
 * @method string getLastIncreaseTime()
 * @method void setLastIncreaseTime(\string $value)
 * @method string getLastDecreaseTime()
 * @method void setLastDecreaseTime(\string $value)
 * @method string getNumberOfDecreasesToday()
 * @method void setNumberOfDecreasesToday(\string $value)
 */
class ReservedThroughputDetails extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.ReservedThroughputDetails)
  
  /**
   * @var \ots\protocolbuffer\CapacityUnit $capacity_unit
   * @tag 1
   * @label required
   * @type \ProtocolBuffers::TYPE_MESSAGE
   **/
  protected $capacity_unit;
  
  /**
   * @var string $last_increase_time
   * @tag 2
   * @label required
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $last_increase_time;
  
  /**
   * @var string $last_decrease_time
   * @tag 3
   * @label optional
   * @type \ProtocolBuffers::TYPE_INT64
   **/
  protected $last_decrease_time;
  
  /**
   * @var string $number_of_decreases_today
   * @tag 4
   * @label required
   * @type \ProtocolBuffers::TYPE_INT32
   **/
  protected $number_of_decreases_today;
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.ReservedThroughputDetails)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.ReservedThroughputDetails)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "capacity_unit",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\CapacityUnit',
      )));
      $desc->addField(2, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "last_increase_time",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(3, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT64,
        "name"     => "last_decrease_time",
        "required" => false,
        "optional" => true,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      $desc->addField(4, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_INT32,
        "name"     => "number_of_decreases_today",
        "required" => true,
        "optional" => false,
        "repeated" => false,
        "packable" => false,
        "default"  => null,
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.ReservedThroughputDetails)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
