<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.RowExistenceExpectation)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 */
class RowExistenceExpectation extends \ProtocolBuffers\Enum
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.RowExistenceExpectation)
  
  const IGNORE = 0;
  const EXPECT_EXIST = 1;
  const EXPECT_NOT_EXIST = 2;
  
  // @@protoc_insertion_point(const_scope:.ots.protocolbuffer.RowExistenceExpectation)
  
  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.RowExistenceExpectation)
  
  /**
   * @return \ProtocolBuffers\EnumDescriptor
   */
  public static function getEnumDescriptor()
  {
    static $descriptor;
    if (!$descriptor) {
      $builder = new \ProtocolBuffers\EnumDescriptorBuilder();
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::IGNORE,
        "name"  => 'IGNORE',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::EXPECT_EXIST,
        "name"  => 'EXPECT_EXIST',
      )));
      $builder->addValue(new \ProtocolBuffers\EnumValueDescriptor(array(
        "value" => self::EXPECT_NOT_EXIST,
        "name"  => 'EXPECT_NOT_EXIST',
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.RowExistenceExpectation)
      $descriptor = $builder->build();
    }
    return $descriptor;
  }
}
