<?php
namespace ots\protocolbuffer;

// @@protoc_insertion_point(namespace:.ots.protocolbuffer.RowInBatchGetRowRequest)

/**
 * Generated by the protocol buffer compiler.  DO NOT EDIT!
 * source: ots_protocol_buffer.proto
 *
 * BatchGetRow
 *
 * -*- magic methods -*-
 *
 * @method array getPrimaryKey()
 * @method void appendPrimaryKey(\ots\protocolbuffer\Column $value)
 */
class RowInBatchGetRowRequest extends \ProtocolBuffers\Message
{
  // @@protoc_insertion_point(traits:.ots.protocolbuffer.RowInBatchGetRowRequest)
  
  /**
   * @var array $primary_key
   * @tag 1
   * @label optional
   * @type \ProtocolBuffers::TYPE_MESSAGE
   * @see \ots\protocolbuffer\Column
   **/
  protected $primary_key;
  
  
  // @@protoc_insertion_point(properties_scope:.ots.protocolbuffer.RowInBatchGetRowRequest)

  // @@protoc_insertion_point(class_scope:.ots.protocolbuffer.RowInBatchGetRowRequest)

  /**
   * get descriptor for protocol buffers
   * 
   * @return \ProtocolBuffersDescriptor
   */
  public static function getDescriptor()
  {
    static $descriptor;
    
    if (!isset($descriptor)) {
      $desc = new \ProtocolBuffers\DescriptorBuilder();
      $desc->addField(1, new \ProtocolBuffers\FieldDescriptor(array(
        "type"     => \ProtocolBuffers::TYPE_MESSAGE,
        "name"     => "primary_key",
        "required" => false,
        "optional" => false,
        "repeated" => true,
        "packable" => false,
        "default"  => null,
        "message" => '\ots\protocolbuffer\Column',
      )));
      // @@protoc_insertion_point(builder_scope:.ots.protocolbuffer.RowInBatchGetRowRequest)

      $descriptor = $desc->build();
    }
    return $descriptor;
  }

}
